steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/useful-circle-444209-q7/image-function-v2', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/useful-circle-444209-q7/image-function-v2']

  # Step 3: Deploy the Docker container (e.g., to Cloud Run or Cloud Functions)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'image-function-v2',
      '--image', 'gcr.io/useful-circle-444209-q7/image-function-v2',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/useful-circle-444209-q7/image-function-v2'

timeout: 1200s
